Repository workday-group-3/referee-handbook-Frontend, pull requests merged in 2022-07, with the labels that each got.

#27 Setup connection to the backend, and creating method in apiClient to …
  src/components/CoursesListPage/CoursesListPage.jsx
  src/services/apiClient.js
Labels: enhancement

#34 Added a difficulty option in course form, each sport category in lear…
  src/components/CoursesListPage/CoursesListPage.css
  src/components/CoursesListPage/CoursesListPage.jsx
  src/components/CreateCourseForm/CreateCourseForm.css
  src/components/CreateCourseForm/CreateCourseForm.jsx
  src/components/LearningSubBanner/LearningSubBanner.css
Labels: enhancement

#36 User course img hotfix
  src/components/CoursesListPage/CoursesListPage.css
  src/components/CoursesListPage/CoursesListPage.jsx
  src/services/apiClient.js
Labels: enhancement

#37 fixed minor naming bug for grid
  src/components/HomeTeamsGrid/HomeTeamsGrid.jsx
  src/contexts/home.jsx
Labels: enhancement

#38 CSS fixes for create button overflowing into footer
  src/components/CreateCourseForm/CreateCourseForm.css
  src/components/CreateCourseForm/CreateCourseForm.jsx
  src/components/ProfilePage/ProfilePage.css
Labels: bug

#42 Removed text-decoration from each user course and other minor css cha…
  src/components/CoursesListPage/CoursesListPage.css
  src/components/CoursesListPage/CoursesListPage.jsx
Labels: enhancement

#43 Created a team page which renders basic information about the team and set up routing
  src/components/App/App.jsx
  src/components/HomeTeamsCard/HomeTeamsCard.jsx
  src/components/TeamPage/TeamPage.jsx
  src/contexts/home.jsx
Labels: enhancement

#44 Beginner course css overhaul
  src/components/BeginnerCoursePage/BeginnerCoursePage.css
  src/components/BeginnerCoursePage/BeginnerCoursePage.jsx
  src/components/Carousel/Carousel.css
  src/components/Carousel/Carousel.jsx
  src/components/LearningCenterPage/LearningCenterPage.css
  src/components/LearningSubBanner/LearningSubBanner.css
  src/components/LearningSubBanner/LearningSubBanner.jsx
  src/components/UserCreatedCoursePage/UserCreatedCoursePage.jsx
  src/globals.css
Labels: enhancement

#45 Added frontend functionality for users to be able to follow a sports …
  src/components/TeamPage/TeamPage.jsx
  src/contexts/home.jsx
  src/services/apiClient.js
Labels: enhancement

#46 Detailed team page renders 3 recent games
  src/components/HomeRecentGames/HomeRecentGames.jsx
  src/components/TeamGamesCard/TeamGamesCard.jsx
  src/components/TeamGamesGrid/TeamGamesGrid.jsx
  src/components/TeamPage/TeamPage.jsx
  src/contexts/home.jsx
Labels: enhancement

#47 User course css overhaul
  src/components/UserCreatedCoursePage/UserCreatedCoursePage.css
  src/components/UserCreatedCoursePage/UserCreatedCoursePage.jsx
Labels: enhancement

#48 styled team page according to wireframe
  src/components/TeamGamesCard/TeamGamesCard.css
  src/components/TeamGamesCard/TeamGamesCard.jsx
  src/components/TeamGamesGrid/TeamGamesGrid.css
  src/components/TeamGamesGrid/TeamGamesGrid.jsx
  src/components/TeamPage/TeamPage.css
  src/components/TeamPage/TeamPage.jsx
  src/contexts/home.jsx
Labels: enhancement

#50 Users are now able to view their followed teams on their profile page
  src/components/ProfilePage/ProfilePage.css
  src/components/ProfilePage/ProfilePage.jsx
  src/services/apiClient.js
Labels: enhancement

#51 Added message if the api reaches the limit and a return button
  src/components/HomeNews/HomeNews.jsx
  src/components/HomeRecentGames/HomeRecentGames.jsx
  src/components/HomeTeamsGrid/HomeTeamsGrid.css
  src/components/HomeTeamsGrid/HomeTeamsGrid.jsx
  src/components/TeamPage/TeamPage.css
  src/components/TeamPage/TeamPage.jsx
  src/contexts/home.jsx
Labels: enhancement

#52 fixed bugs in displaying the limit , removed like button from sub ban…
  src/components/LearningSubBanner/LearningSubBanner.jsx
  src/contexts/home.jsx
Labels: enhancement

#54 Profile css edits
  src/components/CoursesListPage/CoursesListPage.css
  src/components/CoursesListPage/CoursesListPage.jsx
  src/components/CreateCourseForm/CreateCourseForm.jsx
  src/components/ProfilePage/ProfilePage.css
  src/components/ProfilePage/ProfilePage.jsx
  src/components/RegisterPage/RegisterPage.css
Labels: enhancement

#53 Course form popup
  src/components/CreateCourseForm/CreateCourseForm.css
  src/components/CreateCourseForm/CreateCourseForm.jsx
  src/components/MarkdownModal/MarkdownModal.css
  src/components/MarkdownModal/MarkdownModal.jsx
  src/components/MarkdownPreviewModal/MarkdownPreviewModal.css
  src/components/MarkdownPreviewModal/MarkdownPreviewModal.jsx
Labels: enhancement

#55 Markdown implementation
  package-lock.json
  package.json
  src/assets/soccer-banner.jpg
  src/components/App/App.jsx
  src/components/BeginnerCoursePage/BeginnerCoursePage.css
  src/components/BeginnerCoursePage/BeginnerCoursePage.jsx
  src/components/Carousel/Carousel.css
  src/components/Carousel/Carousel.jsx
  src/components/CoursesListPage/CoursesListPage.css
  src/components/CoursesListPage/CoursesListPage.jsx
  src/components/CreateCourseForm/CreateCourseForm.css
  src/components/CreateCourseForm/CreateCourseForm.jsx
  src/components/Footer/Footer.jsx
  src/components/HomeBanner/HomeBanner.jsx
  src/components/HomeNews/HomeNews.jsx
  src/components/HomePage/HomePage.css
  src/components/HomeRecentGames/HomeRecentGames.css
  src/components/HomeRecentGames/HomeRecentGames.jsx
  src/components/HomeSideNavbar/HomeSideNavbar.jsx
  src/components/HomeTeamsCard/HomeTeamsCard.jsx
  src/components/HomeTeamsGrid/HomeTeamsGrid.css
  src/components/HomeTeamsGrid/HomeTeamsGrid.jsx
  src/components/LearningCenterCard/LearningCenterCard.jsx
  src/components/LearningCenterPage/LearningCenterPage.css
  src/components/LearningCenterPage/LearningCenterPage.jsx
  src/components/LearningSubBanner/LearningSubBanner.css
  src/components/LearningSubBanner/LearningSubBanner.jsx
  src/components/MarkdownModal/MarkdownModal.css
  src/components/MarkdownModal/MarkdownModal.jsx
  src/components/MarkdownPreviewModal/MarkdownPreviewModal.css
  src/components/MarkdownPreviewModal/MarkdownPreviewModal.jsx
  src/components/ProfilePage/ProfilePage.css
  src/components/ProfilePage/ProfilePage.jsx
  src/components/RegisterPage/RegisterPage.css
  src/components/TeamGamesCard/TeamGamesCard.css
  src/components/TeamGamesCard/TeamGamesCard.jsx
  src/components/TeamGamesGrid/TeamGamesGrid.css
  src/components/TeamGamesGrid/TeamGamesGrid.jsx
  src/components/TeamPage/TeamPage.css
  src/components/TeamPage/TeamPage.jsx
  src/components/UserCreatedCoursePage/UserCreatedCoursePage.css
  src/components/UserCreatedCoursePage/UserCreatedCoursePage.jsx
  src/contexts/home.jsx
  src/globals.css
  src/services/apiClient.js
Labels: enhancement

#57 team page now pulls from live api instead of hardcode data
  .gitignore
  src/components/HomeTeamsCard/HomeTeamsCard.css
  src/components/ProfilePage/ProfilePage.css
  src/components/ProfilePage/ProfilePage.jsx
  src/components/TeamGamesGrid/TeamGamesGrid.jsx
  src/components/TeamPage/TeamPage.jsx
  src/contexts/home.jsx
  src/services/apiClient.js
Labels: enhancement

#58 Merge bug fixes and live api features from release train
  .gitignore
  src/components/App/App.jsx
  src/components/CoursesListPage/CoursesListPage.jsx
  src/components/HomeTeamsCard/HomeTeamsCard.css
  src/components/ProfilePage/ProfilePage.css
  src/components/ProfilePage/ProfilePage.jsx
  src/components/ScrollToTop/ScrollToTop.jsx
  src/components/TeamGamesGrid/TeamGamesGrid.jsx
  src/components/TeamPage/TeamPage.jsx
  src/contexts/home.jsx
Labels: enhancement

#59 Tips tricks markdown
  src/components/CreateCourseForm/CreateCourseForm.jsx
  src/components/UserCreatedCoursePage/UserCreatedCoursePage.css
  src/components/UserCreatedCoursePage/UserCreatedCoursePage.jsx
Labels: enhancement

#68 Changed route name for sports home page from "home" to "sports"
  src/components/App/App.jsx
  src/components/NavLinks/NavLinks.jsx
Labels: enhancement

#73 User courses css fix
  src/components/LearningSubBanner/LearningSubBanner.css
  src/components/LearningSubBanner/LearningSubBanner.jsx
  src/components/UserCreatedCoursePage/UserCreatedCoursePage.css
  src/components/UserCreatedCoursePage/UserCreatedCoursePage.jsx
Labels: bug

#74 added active navlink styling
  src/components/NavLinks/NavLinks.css
  src/components/NavLinks/NavLinks.jsx
  src/components/TeamPage/TeamPage.jsx
Labels: enhancement

#75 Profile page team redirect
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/ProfilePage/ProfilePage.css
  src/components/ProfilePage/ProfilePage.jsx
  src/services/apiClient.js
Labels: enhancement

#76 Enhancements for home page
  src/components/HomeNews/HomeNews.css
  src/components/HomeNews/HomeNews.jsx
  src/components/HomeNewsCard/HomeNewsCard.css
  src/components/HomeNewsCard/HomeNewsCard.jsx
  src/components/HomeRecentGames/HomeRecentGames.css
  src/components/HomeRecentGames/HomeRecentGames.jsx
  src/components/HomeSideNavbar/HomeSideNavbar.css
  src/components/HomeTeamsGrid/HomeTeamsGrid.css
  src/components/HomeTeamsGrid/HomeTeamsGrid.jsx
  src/contexts/home.jsx
Labels: enhancement

#77 Informative video messages
  src/components/CoursesListPage/CoursesListPage.css
  src/components/CoursesListPage/CoursesListPage.jsx
  src/components/CreateCourseForm/CreateCourseForm.jsx
  src/components/LearningSubBanner/LearningSubBanner.css
  src/components/UserCreatedCoursePage/UserCreatedCoursePage.css
  src/components/UserCreatedCoursePage/UserCreatedCoursePage.jsx
Labels: bug, enhancement

#78 Api enhancements and error message rendering
  .env.template
  src/components/HomeNews/HomeNews.jsx
  src/components/HomeRecentGames/HomeRecentGames.jsx
  src/components/HomeTeamsGrid/HomeTeamsGrid.jsx
  src/components/NavLinks/NavLinks.jsx
  src/components/TeamGamesGrid/TeamGamesGrid.jsx
  src/components/TeamPage/TeamPage.jsx
  src/contexts/home.jsx
Labels: enhancement

#79 Removed console logs, profile page now adds course to local storage w…
  src/components/CoursesListPage/CoursesListPage.jsx
  src/components/LoginPage/LoginPage.jsx
  src/components/ProfilePage/ProfilePage.jsx
  src/components/UserCreatedCoursePage/UserCreatedCoursePage.jsx
  src/contexts/auth.jsx
  src/hooks/useLoginForm.jsx
  src/hooks/useRegistrationForm.jsx
Labels: bug

#80 Broken images
  src/components/CoursesListPage/CoursesListPage.jsx
  src/components/Navbar/Navbar.css
  src/components/UserCreatedCoursePage/UserCreatedCoursePage.css
  src/components/UserCreatedCoursePage/UserCreatedCoursePage.jsx
Labels: bug, enhancement

#81 create a course form now has an expandable long description.
  src/components/CreateCourseForm/CreateCourseForm.jsx
Labels: documentation, enhancement

#82 Added maxLength tags to all textfields
  src/components/CreateCourseForm/CreateCourseForm.jsx
  src/components/LoginPage/LoginPage.jsx
  src/components/RegisterPage/RegisterPage.jsx
Labels: enhancement

#83 Added more resources to footer, profile page now has a redirect to sp…
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/ProfilePage/ProfilePage.jsx
Labels: enhancement

#86 Fixed learning center sub navbar conflicting with original navbar
  src/components/CoursesListPage/CoursesListPage.css
  src/components/LearningSubBanner/LearningSubBanner.css
  src/components/Navbar/Navbar.css
Labels: bug

#87 Create course from profile
  src/components/DropDownCreate/DropDownCreate.css
  src/components/DropDownCreate/DropDownCreate.jsx
  src/components/EmailUs/EmailUs.jsx
  src/components/LearningCenterCard/LearningCenterCard.css
  src/components/LearningCenterPage/LearningCenterPage.css
  src/components/LearningCenterPage/LearningCenterPage.jsx
  src/components/ProfilePage/ProfilePage.css
  src/components/ProfilePage/ProfilePage.jsx
Labels: enhancement

#89 minor fix. sub navbar overcrowded timeline and user created course pa…
  src/components/BeginnerCoursePage/BeginnerCoursePage.css
  src/components/UserCreatedCoursePage/UserCreatedCoursePage.css
Labels: bug
